/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nn_bsdiff_BSDiff */

#ifndef _Included_com_nn_bsdiff_BSDiff
#define _Included_com_nn_bsdiff_BSDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nn_bsdiff_BSDiff
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_nn_bsdiff_BSDiff_diff
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_nn_bsdiff_BSDiff
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_nn_bsdiff_BSDiff_patch
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
